### ISSUE TITLE
Enable Travis CI / Circle CI

### ISSUE THREAD

**Issue by DanielRuf** [daniel-lundin/dom-confetti#12]

**Comment by daniel-lundin** [comment]
It it a problem running CI with this library?

**Comment by DanielRuf** [comment]
> It it a problem running CI with this library?

I don't understand what you mean.
In general automatically checking if `npm start`, `npm test` and so on work it helpful to catch issues early and make sure that nothing breaks.

Enabling Travis CI or another CI solution is not hard and I would help here.
