### ISSUE TITLE
Wrong typings in index.d.ts

### ISSUE THREAD

**Issue by RyannGalea** [daniel-lundin/dom-confetti#19]
interface ConfettiConfig {
    angle?: number;
    spread?: number;
    width?: number; *** string
    height?: number; *** string
    duration?: number; *** Currently missing completely
    startVelocity?: number;
    elementCount?: number;
    decay?: number;
    colors?: string[];
    random?: () => number;
}

**Comment by daniel-lundin** [comment]
Oh, forgot about the typings in the latest releases. Will update

**Comment by fabiolapa** [comment]
was this ever updated?

**Comment by acidio** [comment]
Hi @daniel-lundin, could you maybe check whether my PR helps solving this issue?

**Comment by fabiolapa** [comment]
it does btw @acidio

**Comment by daniel-lundin** [comment]
Fixed in 0.1.1. Sorry for the delay.
